### ISSUE TITLE
Installation nicht möglich

### ISSUE THREAD

**Issue by olien** [joachimdoerr/mcalendar#1]
AddOn mcalendar konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "SHOW COLUMNS FROM rex_mcalendar_categories"! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd8.rex_mcalendar_categories' doesn't exist

**Comment by joachimdoerr** [comment]
das liegt wohl daran, dass zuerst die install.php ausgeführt wird und danach erst die install.sql - da die install.php erstmal die db sprachabhängig überprüft und erweitern will gibt es da Probleme.

**Comment by joachimdoerr** [comment]
ist gefixt: https://github.com/joachimdoerr/mcalendar/commit/467946457369f900fc27e5877791166d4c59ac99
