### ISSUE TITLE
Feature :: Möglichkeit zur Definition von weiteren Feldern

### ISSUE THREAD

**Issue by skerbis** [joachimdoerr/mcalendar#8]
Es wäre toll, wenn die Möglichkeit bestünde weitere, optionale Felder definieren zu können. 
(z.B. Kursnummer, Kurzbeschreibung ... )
Das würde den Kalender sehr flexibel machen. 
Evtl. macht es Sinn den Kalender yform basiert aufzubauen? So dass man den Table Manager nutzen könnte um weitere Eingaben zu realisieren?

**Comment by joachimdoerr** [comment]
feine idee, das könnte man via settings yml erledigen, diese könnte man als textarea editieren und so die default felder ergänzen

**Comment by joachimdoerr** [comment]
Fiedsets können jetzt via json hinzugefügt werden und zwar für jede tabelle siehe: https://github.com/joachimdoerr/mcalendar/blob/master/definitions/events.yml
